/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SetIdLazyImport = createFileRoute('/$setId')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SetIdLazyRoute = SetIdLazyImport.update({
  id: '/$setId',
  path: '/$setId',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/$setId.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/$setId': {
      id: '/$setId'
      path: '/$setId'
      fullPath: '/$setId'
      preLoaderRoute: typeof SetIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/$setId': typeof SetIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/$setId': typeof SetIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/$setId': typeof SetIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$setId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$setId'
  id: '__root__' | '/' | '/$setId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  SetIdLazyRoute: typeof SetIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  SetIdLazyRoute: SetIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$setId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/$setId": {
      "filePath": "$setId.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
